server:
  port: 8002
  servlet:
    context-path: /test  #配置localhost:8080/test下访问

#配置日志 可使用xml 也可以使用配置文件
#logging:
#  config:
#  file:
#    name: test.log

# 配置多个微服务的地址
url:
  # 订单微服务的地址
  orderUrl: http://localhost:8002
  # 用户微服务的地址
  userUrl: http://localhost:8003
  # 购物车微服务的地址
  shoppingUrl: http://localhost:8004
spring:
  datasource:
    url: jdbc:h2:file:~/MyMavenTest
    driver-class-name: org.h2.Driver
    username: sa
    password: 123
  h2:
    console:
      enabled: true
  redis:
    database: 1
    host: 127.0.0.1
    password: 123456
    port: 6379
    timeout: 5000
    jedis:
      pool:
        # 连接池中的最大空闲连接，默认值也是8。
        max-idle: 500
        # 连接池中的最小空闲连接，默认值也是0。
        min-idle: 50
        # 如果赋值为-1，则表示不限制；如果pool已经分配了maxActive个jedis实例，则此时pool的状态为exhausted(耗尽)
        max-active: 1000
        # 等待可用连接的最大时间，单位毫秒，默认值为-1，表示永不超时。如果超过等待时间，则直接抛出JedisConnectionException
        max-wait: 2000
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
  activemq:
    broker-url: tcp://localhost:61616
    in-memory: true
    pool:
      # 如果此处设置为true，需要添加activemq-pool的依赖包，否则会自动配置失败，无法注入JmsMessagingTemplate
      enabled: false
    user: admin
    password: admin
    #邮件配置
  mail:
    host: smtp.qq.com
    port: 465
    username: #邮箱地址
    password: #自己的授权码
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          ssl:
            enable: true

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
