server:
  port: 8002
  servlet:
    context-path: /test  #配置localhost:8080/test下访问

#配置日志 可使用xml 也可以使用配置文件
logging:
  config:
  file:
    name: test.log

# 配置多个微服务的地址
url:
  # 订单微服务的地址
  orderUrl: http://localhost:8002
  # 用户微服务的地址
  userUrl: http://localhost:8003
  # 购物车微服务的地址
  shoppingUrl: http://localhost:8004
spring:
  datasource:
    url: jdbc:h2:file:~/MyMavenTest
    driver-class-name: org.h2.Driver
    username: sa
    password: 123
  h2:
    console:
      enabled: true
